export const CREATE_GRID = 'CREATE_GRID';
export const SELECT_BLOCK = 'SELECT_BLOCK';
export const UNSELECT_BLOCK = 'UNSELECT_BLOCK';
export const FILL_BLOCK = 'FILL_BLOCK';
export const ENABLE_VALIDATION = 'ENABLE_VALIDATION';
export const DISABLE_VALIDATION = 'DISABLE_VALIDATION';
export const DISPLAY_SUDOKU_TEMPLATE = 'DISPLAY_SUDOKU_TEMPLATE';
export const HIDE_SUDOKU_TEMPLATE = 'HIDE_SUDOKU_TEMPLATE ';
